// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pb/consumer/proto/proxy.proto

package consumer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeStatus int32

const (
	ChangeStatus_Failed  ChangeStatus = 0
	ChangeStatus_Success ChangeStatus = 1
)

// Enum value maps for ChangeStatus.
var (
	ChangeStatus_name = map[int32]string{
		0: "Failed",
		1: "Success",
	}
	ChangeStatus_value = map[string]int32{
		"Failed":  0,
		"Success": 1,
	}
)

func (x ChangeStatus) Enum() *ChangeStatus {
	p := new(ChangeStatus)
	*p = x
	return p
}

func (x ChangeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_consumer_proto_proxy_proto_enumTypes[0].Descriptor()
}

func (ChangeStatus) Type() protoreflect.EnumType {
	return &file_pb_consumer_proto_proxy_proto_enumTypes[0]
}

func (x ChangeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeStatus.Descriptor instead.
func (ChangeStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_consumer_proto_proxy_proto_rawDescGZIP(), []int{0}
}

type NotifyNewProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessID        string `protobuf:"bytes,1,opt,name=sessID,proto3" json:"sessID,omitempty"`
	UserID        string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ProviderID    string `protobuf:"bytes,3,opt,name=providerID,proto3" json:"providerID,omitempty"`
	AccessPointID string `protobuf:"bytes,4,opt,name=accessPointID,proto3" json:"accessPointID,omitempty"`
}

func (x *NotifyNewProviderRequest) Reset() {
	*x = NotifyNewProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_consumer_proto_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewProviderRequest) ProtoMessage() {}

func (x *NotifyNewProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_consumer_proto_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewProviderRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewProviderRequest) Descriptor() ([]byte, []int) {
	return file_pb_consumer_proto_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyNewProviderRequest) GetSessID() string {
	if x != nil {
		return x.SessID
	}
	return ""
}

func (x *NotifyNewProviderRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *NotifyNewProviderRequest) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *NotifyNewProviderRequest) GetAccessPointID() string {
	if x != nil {
		return x.AccessPointID
	}
	return ""
}

type ChangeProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcknowledgmentID string       `protobuf:"bytes,1,opt,name=AcknowledgmentID,proto3" json:"AcknowledgmentID,omitempty"`
	Status           ChangeStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=zchain.pb.consumer.ChangeStatus" json:"Status,omitempty"`
}

func (x *ChangeProviderResponse) Reset() {
	*x = ChangeProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_consumer_proto_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProviderResponse) ProtoMessage() {}

func (x *ChangeProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_consumer_proto_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProviderResponse.ProtoReflect.Descriptor instead.
func (*ChangeProviderResponse) Descriptor() ([]byte, []int) {
	return file_pb_consumer_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeProviderResponse) GetAcknowledgmentID() string {
	if x != nil {
		return x.AcknowledgmentID
	}
	return ""
}

func (x *ChangeProviderResponse) GetStatus() ChangeStatus {
	if x != nil {
		return x.Status
	}
	return ChangeStatus_Failed
}

var File_pb_consumer_proto_proxy_proto protoreflect.FileDescriptor

var file_pb_consumer_proto_proxy_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x18, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65,
	0x77, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x73, 0x73, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x7e, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x41, 0x63, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x7a,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x27, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x32,
	0x76, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x6d, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x2c, 0x2e,
	0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x7a, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x61, 0x6e,
	0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_consumer_proto_proxy_proto_rawDescOnce sync.Once
	file_pb_consumer_proto_proxy_proto_rawDescData = file_pb_consumer_proto_proxy_proto_rawDesc
)

func file_pb_consumer_proto_proxy_proto_rawDescGZIP() []byte {
	file_pb_consumer_proto_proxy_proto_rawDescOnce.Do(func() {
		file_pb_consumer_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_consumer_proto_proxy_proto_rawDescData)
	})
	return file_pb_consumer_proto_proxy_proto_rawDescData
}

var file_pb_consumer_proto_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_consumer_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_consumer_proto_proxy_proto_goTypes = []interface{}{
	(ChangeStatus)(0),                // 0: zchain.pb.consumer.ChangeStatus
	(*NotifyNewProviderRequest)(nil), // 1: zchain.pb.consumer.NotifyNewProviderRequest
	(*ChangeProviderResponse)(nil),   // 2: zchain.pb.consumer.ChangeProviderResponse
}
var file_pb_consumer_proto_proxy_proto_depIdxs = []int32{
	0, // 0: zchain.pb.consumer.ChangeProviderResponse.Status:type_name -> zchain.pb.consumer.ChangeStatus
	1, // 1: zchain.pb.consumer.Proxy.NotifyNewProvider:input_type -> zchain.pb.consumer.NotifyNewProviderRequest
	2, // 2: zchain.pb.consumer.Proxy.NotifyNewProvider:output_type -> zchain.pb.consumer.ChangeProviderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_consumer_proto_proxy_proto_init() }
func file_pb_consumer_proto_proxy_proto_init() {
	if File_pb_consumer_proto_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_consumer_proto_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyNewProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_consumer_proto_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_consumer_proto_proxy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_consumer_proto_proxy_proto_goTypes,
		DependencyIndexes: file_pb_consumer_proto_proxy_proto_depIdxs,
		EnumInfos:         file_pb_consumer_proto_proxy_proto_enumTypes,
		MessageInfos:      file_pb_consumer_proto_proxy_proto_msgTypes,
	}.Build()
	File_pb_consumer_proto_proxy_proto = out.File
	file_pb_consumer_proto_proxy_proto_rawDesc = nil
	file_pb_consumer_proto_proxy_proto_goTypes = nil
	file_pb_consumer_proto_proxy_proto_depIdxs = nil
}
