version: '3'
services:
  docker-clean:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # 1-6 consumers
      - ../consumer1/:/consumer1
      - ../consumer2/:/consumer2
      - ../consumer3/:/consumer3
      - ../consumer4/:/consumer4
      - ../consumer5/:/consumer5
      - ../consumer6/:/consumer6
    command: /bin/sh docker-clean.sh

volumes:
  consumer1:
  consumer2:
  consumer3:
  consumer4:
  consumer5:
  consumer6:
