server_chain:
  id: ""
  owner_id: ""
  signature_scheme: "bls0chain"

  # Represents dns address.
  block_worker: http://198.18.0.98:9091

handler:
  # per second
  rate_limit: 10

db:
  name: consumer_meta
  user: consumer_user
  password: consumer
  host: postgres
  port: 5432

logging:
  level: "info"

# Represents address of magma service.
magma_address: "198.18.0.21:7051"

hss:
  # Represents pre configured registered users.
  users: [
      "ad48a91f6cac943805a60c143986644d861639ed9cde711de5135b6de95cb74b",
  ]

proxy:
  # Represents configuration which determines consumer's decision about accepting provider terms.
  terms:
    # token per MB
    max_price: 5

    qos:
      # megabits per second
      min_download_bmps: 10

      # megabits per second
      min_upload_bmps: 10

# in seconds
grpc_server_timeout: 15