server_chain:
  id: ""
  owner_id: ""
  signature_scheme: "bls0chain"

  # Represents dns address.
  block_worker: http://198.18.0.98:9091

handler:
  # per second
  rate_limit: 10

db:
  name: consumer_meta
  user: consumer_user
  password: consumer
  host: postgres
  port: 5432

logging:
  level: "info"

# Represents address of magma service.
magma_address: "198.18.0.21:7051"

proxy:
  # Represents configuration which determines consumer's decision about accepting provider terms.
  terms:
    # token per MB
    max_price: 5

    qos:
      # megabits per second
      min_download_bmps: 10

      # megabits per second
      min_upload_bmps: 10

# in seconds
grpc_server_timeout: 30