port: 5081

grpc_address: ":7051"

logging:
  level: "info"
  dir: "/magma/log"

handler:
  rate_limit: 10 # per second

consumer:
  hss:
    address: ":7031"

consumer_address: "198.18.0.91:7031"

provider_address: "198.18.0.11:7041"

# in seconds
grpc_server_timeout: 30