port: 5081

grpc_address: ":7051"

logging:
  level: "info"
  dir: "/magma/log"

handler:
  rate_limit: 10 # per second

consumer:
  hss:
    address: ":7031"

consumer_address: "198.18.0.91:7031"

provider_address: "198.18.0.11:7041"

# in seconds
grpc_server_timeout: 50

# TODO: temp, need to find better solution
id_maps:
  consumer:
    man_feg_network: f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
  provider:
    man_embedded_cwag_network: 7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d