server_chain:
  id: ""
  owner_id: ""
  signature_scheme: "bls0chain"

  # Represents dns address.
  block_worker: http://198.18.0.98:9091

handler:
  # per second
  rate_limit: 10

db:
  name: provider_meta
  user: provider_user
  password: provider
  host: postgres
  port: 5432

logging:
  level: "debug"

# Use this section to configure terms of provider. Configuration is being used only while registration process.
# If node already registered in blockchain, you should update terms manually using cli client.
terms:
  # token per megabyte
  price: 1

  volume: 1

  # will be used as `expired_at`(in minutes) + current registration time
  expired_at: 8650 # 1 year

  qos:
    # megabits per second
    download_mbps: 10

    # megabits per second
    upload_mbps: 10

magma_address: "198.18.0.21:7051"

access_point_id: "access point id"

# in seconds
grpc_server_timeout: 30