// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package magma

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MagmaClient is the client API for Magma service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MagmaClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type magmaClient struct {
	cc grpc.ClientConnInterface
}

func NewMagmaClient(cc grpc.ClientConnInterface) MagmaClient {
	return &magmaClient{cc}
}

func (c *magmaClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/zchain.pb.magma.Magma/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagmaServer is the server API for Magma service.
// All implementations must embed UnimplementedMagmaServer
// for forward compatibility
type MagmaServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedMagmaServer()
}

// UnimplementedMagmaServer must be embedded to have forward compatible implementations.
type UnimplementedMagmaServer struct {
}

func (UnimplementedMagmaServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMagmaServer) mustEmbedUnimplementedMagmaServer() {}

// UnsafeMagmaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagmaServer will
// result in compilation errors.
type UnsafeMagmaServer interface {
	mustEmbedUnimplementedMagmaServer()
}

func RegisterMagmaServer(s grpc.ServiceRegistrar, srv MagmaServer) {
	s.RegisterService(&Magma_ServiceDesc, srv)
}

func _Magma_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagmaServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zchain.pb.magma.Magma/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagmaServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Magma_ServiceDesc is the grpc.ServiceDesc for Magma service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Magma_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zchain.pb.magma.Magma",
	HandlerType: (*MagmaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Magma_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/magma/proto/magma.proto",
}
