// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pb/magma/proto/magma.proto

package magma

import (
	consumer "github.com/0chain/bandwidth_marketplace/code/pb/consumer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Failed    Status = 0
	Status_Connected Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Failed",
		1: "Connected",
	}
	Status_value = map[string]int32{
		"Failed":    0,
		"Connected": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_magma_proto_magma_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pb_magma_proto_magma_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_magma_proto_magma_proto_rawDescGZIP(), []int{0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        string         `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConsumerID    string         `protobuf:"bytes,2,opt,name=consumerID,proto3" json:"consumerID,omitempty"`
	ProviderID    string         `protobuf:"bytes,3,opt,name=providerID,proto3" json:"providerID,omitempty"`
	AccessPointID string         `protobuf:"bytes,5,opt,name=accessPointID,proto3" json:"accessPointID,omitempty"`
	Auth          *consumer.Auth `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_magma_proto_magma_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_magma_proto_magma_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_pb_magma_proto_magma_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ConnectRequest) GetConsumerID() string {
	if x != nil {
		return x.ConsumerID
	}
	return ""
}

func (x *ConnectRequest) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *ConnectRequest) GetAccessPointID() string {
	if x != nil {
		return x.AccessPointID
	}
	return ""
}

func (x *ConnectRequest) GetAuth() *consumer.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=zchain.pb.magma.Status" json:"status,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_magma_proto_magma_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_magma_proto_magma_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_pb_magma_proto_magma_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Failed
}

var File_pb_magma_proto_magma_proto protoreflect.FileDescriptor

var file_pb_magma_proto_magma_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x7a, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x1a, 0x1b, 0x70,
	0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x7a, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x42, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x7a,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x23, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x10, 0x01, 0x32, 0x55, 0x0a, 0x05, 0x4d, 0x61, 0x67, 0x6d, 0x61, 0x12, 0x4c, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x7a, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_magma_proto_magma_proto_rawDescOnce sync.Once
	file_pb_magma_proto_magma_proto_rawDescData = file_pb_magma_proto_magma_proto_rawDesc
)

func file_pb_magma_proto_magma_proto_rawDescGZIP() []byte {
	file_pb_magma_proto_magma_proto_rawDescOnce.Do(func() {
		file_pb_magma_proto_magma_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_magma_proto_magma_proto_rawDescData)
	})
	return file_pb_magma_proto_magma_proto_rawDescData
}

var file_pb_magma_proto_magma_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_magma_proto_magma_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_magma_proto_magma_proto_goTypes = []interface{}{
	(Status)(0),             // 0: zchain.pb.magma.Status
	(*ConnectRequest)(nil),  // 1: zchain.pb.magma.ConnectRequest
	(*ConnectResponse)(nil), // 2: zchain.pb.magma.ConnectResponse
	(*consumer.Auth)(nil),   // 3: zchain.pb.consumer.Auth
}
var file_pb_magma_proto_magma_proto_depIdxs = []int32{
	3, // 0: zchain.pb.magma.ConnectRequest.auth:type_name -> zchain.pb.consumer.Auth
	0, // 1: zchain.pb.magma.ConnectResponse.status:type_name -> zchain.pb.magma.Status
	1, // 2: zchain.pb.magma.Magma.Connect:input_type -> zchain.pb.magma.ConnectRequest
	2, // 3: zchain.pb.magma.Magma.Connect:output_type -> zchain.pb.magma.ConnectResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_magma_proto_magma_proto_init() }
func file_pb_magma_proto_magma_proto_init() {
	if File_pb_magma_proto_magma_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_magma_proto_magma_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_magma_proto_magma_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_magma_proto_magma_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_magma_proto_magma_proto_goTypes,
		DependencyIndexes: file_pb_magma_proto_magma_proto_depIdxs,
		EnumInfos:         file_pb_magma_proto_magma_proto_enumTypes,
		MessageInfos:      file_pb_magma_proto_magma_proto_msgTypes,
	}.Build()
	File_pb_magma_proto_magma_proto = out.File
	file_pb_magma_proto_magma_proto_rawDesc = nil
	file_pb_magma_proto_magma_proto_goTypes = nil
	file_pb_magma_proto_magma_proto_depIdxs = nil
}
