version: "3"
services:
  postgres:
    image: postgres:11
    volumes:
      - ./provider${PROVIDER}/data/postgresql:/var/lib/postgresql/data
    networks:
      default:
    ports:
      - "543${PROVIDER}:5433"
  postgres-post:
    image: postgres:11
    environment:
      POSTGRES_PORT: 5433
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../bin:/provider/bin
      - ../sql/provider:/provider/sql
    command: bash /provider/bin/prov-postgres-entrypoint.sh
    links:
      - postgres:postgres

  provider:
    image: provider
    volumes:
      - ../config:/provider/config
      - ./provider${PROVIDER}/files:/provider/files
      - ./provider${PROVIDER}/data:/provider/data
      - ./provider${PROVIDER}/log:/provider/log
      - ./keys_config/provider:/provider/keys_config
    ports:
      - "506${PROVIDER}:506${PROVIDER}"
      - "704${PROVIDER}:704${PROVIDER}"
    command: ./bin/provider --port 506${PROVIDER} --grpc_port 704${PROVIDER} --hostname localhost --deployment_mode 0 --keys_file keys_config/provider/pnode${PROVIDER}_keys.txt --log_dir /provider/log --db_dir /provider/data
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.1.9${PROVIDER}

networks:
  default:
    driver: bridge
  testnet0:
    external: true
volumes:
  data:
  config:
  bin:
